//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDMSEntities : DbContext
    {
        public EDMSEntities()
            : base("name=EDMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<audit> audits { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<error> errors { get; set; }
        public virtual DbSet<errorLog> errorLogs { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<filetype> filetypes { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<support> supports { get; set; }
    }
}
