//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string filepath { get; set; }
        public Nullable<int> filetypeId { get; set; }
        public int personId { get; set; }
        public string contentType { get; set; }
        public int size { get; set; }
    
        public virtual filetype filetype { get; set; }
        public virtual person person { get; set; }
    }
}
